# Generated by Django 5.2.17 on 2026-09-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tenant_secrets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="decision",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("redo", "Redo"),
                    ("discarded", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
