# Generated by Django 5.2.17 on 2026-09-28 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_approval_reject"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "You"), ("agent", "Agent")], max_length=10
                    ),
                ),
                ("channel", models.CharField(default="web", max_length=20)),
                ("text", models.TextField()),
                ("buttons", models.JSONField(blank=True, default=list)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["created", "id"],
            },
        ),
    ]
