# Generated by Django 5.2.17 on 2026-09-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chat_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='source',
            field=models.CharField(choices=[('rejection', 'Your rejection'), ('manual', 'Written by you'), ('catalyst', 'Catalyst'), ('analyst', 'Analyst fix you approved')], default='manual', max_length=20),
        ),
    ]
